app = "nexaops-api"
primary_region = "bom"

[build]
  dockerfile = "apps/api/Dockerfile"

[env]
  PORT = "8080"
  NODE_ENV = "production"
  NOTIFICATIONS_QUEUE_ENABLED = "true"
  REDIS_TLS = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
